// File generated by FlutterFire CLI.
// Run: dart pub global activate flutterfire_cli && flutterfire configure
//
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Replace this file by running:
///   dart pub global activate flutterfire_cli
///   flutterfire configure
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        // Windows, macOS: use web config
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY-ugyBa-hl8VlrKE_4adWwWcMxmrGP18',
    appId: '1:941909760769:web:3a661ca339f01054ac9900',
    messagingSenderId: '941909760769',
    projectId: 'lastcards-d4396',
    authDomain: 'lastcards-d4396.firebaseapp.com',
    storageBucket: 'lastcards-d4396.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY-ugyBa-hl8VlrKE_4adWwWcMxmrGP18',
    appId: '1:941909760769:android:3a661ca339f01054ac9900',
    messagingSenderId: '941909760769',
    projectId: 'lastcards-d4396',
    storageBucket: 'lastcards-d4396.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY-ugyBa-hl8VlrKE_4adWwWcMxmrGP18',
    appId: '1:941909760769:ios:3a661ca339f01054ac9900',
    messagingSenderId: '941909760769',
    projectId: 'lastcards-d4396',
    storageBucket: 'lastcards-d4396.firebasestorage.app',
    iosBundleId: 'com.example.stackAndFlow',
  );
}
