import 'package:last_cards/shared/engine/game_engine.dart' show buildShuffledDeck;

import '../models/card_model.dart';
import '../models/game_state.dart';
import '../models/player_model.dart';
import 'table_position_layout.dart';

/// Pre-built GameState + shuffled draw pile for offline mode.
///
/// Players:
///   • You        (bottom, human)  — 7 randomly dealt cards
///   • Player 2   (top,    AI)     — 7 randomly dealt cards
///
/// The Dealer is NOT a player. It is the banking entity whose only
/// responsibility is managing the draw pile. No card count, no hand,
/// no turns.
abstract final class OfflineGameState {
  static const localId = 'player-local';
  static const aiId = 'player-2';

  /// Builds the initial [GameState] and the remaining [drawPile] from a single
  /// fresh shuffled deck, dealing cards to each of [totalPlayers] (2 to 7).
  ///
  /// Each player receives exactly 7 cards. Single 54-card deck; max 7 players.
  ///
  /// [aiNames] optionally maps player IDs (`'player-2'` … `'player-7'`) to
  /// human-like random names generated by [AiPlayerConfig.generateForGame].
  ///
  /// [localDisplayName] is the human-controlled seat label (e.g. profile name
  /// from the app layer).
  static (GameState gameState, List<CardModel> drawPile) buildWithDeck({
    int totalPlayers = 2,
    Map<String, String> aiNames = const {},
    String localDisplayName = 'You',
  }) {
    assert(totalPlayers >= 2 && totalPlayers <= 7,
        'totalPlayers must be between 2 and 7');
    final deck = buildShuffledDeck();

    int deckIndex = 0;

    // Fixed 7 cards per hand for all player counts (2–7).
    const handSize = 7;

    // Helper to draw exactly count cards safely
    List<CardModel> draw(int count) {
      final drawn = deck.sublist(deckIndex, deckIndex + count);
      deckIndex += count;
      return drawn;
    }

    // 1. Deal local human
    final localHand = draw(handSize);
    final players = <PlayerModel>[
      PlayerModel(
        id: localId,
        displayName: localDisplayName,
        tablePosition: TablePosition.bottom,
        hand: localHand,
        cardCount: localHand.length,
      ),
    ];

    // 2. Deal AIs — same seat→position mapping as online [GameSession].
    for (int i = 0; i < totalPlayers - 1; i++) {
      final aiHand = draw(handSize);
      players.add(PlayerModel(
        id: 'player-${i + 2}',
        displayName: aiNames['player-${i + 2}'] ?? 'Player ${i + 2}',
        tablePosition: tablePositionForSeatIndex(i + 1),
        hand: aiHand,
        cardCount: aiHand.length,
      ));
    }

    final discardTop = draw(1).first;
    final drawPile = deck.sublist(deckIndex);

    final state = GameState(
      sessionId: 'demo-session',
      phase: GamePhase.playing,
      players: players,
      currentPlayerId: localId,
      direction: PlayDirection.clockwise,
      discardTopCard: discardTop,
      drawPileCount: drawPile.length,
      activePenaltyCount: 0,
      suitLock: null,
      queenSuitLock: null,
      winnerId: null,
    );

    return (state, drawPile);
  }
}
