import 'package:last_cards/shared/engine/game_engine.dart' show buildShuffledDeck;

import '../models/card_model.dart';
import '../models/game_state.dart';
import '../models/player_model.dart';

/// Pre-built GameState + shuffled draw pile for offline mode.
///
/// Players:
///   • You        (bottom, human)  — 7 randomly dealt cards
///   • Player 2   (top,    AI)     — 7 randomly dealt cards
///
/// The Dealer is NOT a player. It is the banking entity whose only
/// responsibility is managing the draw pile. No card count, no hand,
/// no turns.
abstract final class OfflineGameState {
  static const localId = 'player-local';
  static const aiId = 'player-2';

  /// Builds the initial [GameState] and the remaining [drawPile] from a single
  /// fresh shuffled deck, dealing cards to each of [totalPlayers] (2 to 7).
  ///
  /// Each player receives exactly 7 cards. Single 54-card deck; max 7 players.
  ///
  /// [aiNames] optionally maps player IDs (`'player-2'` … `'player-7'`) to
  /// human-like random names generated by [AiPlayerConfig.generateForGame].
  static (GameState gameState, List<CardModel> drawPile) buildWithDeck({
    int totalPlayers = 2,
    Map<String, String> aiNames = const {},
  }) {
    assert(totalPlayers >= 2 && totalPlayers <= 7,
        'totalPlayers must be between 2 and 7');
    final deck = buildShuffledDeck();

    int deckIndex = 0;

    // Fixed 7 cards per hand for all player counts (2–7).
    const handSize = 7;

    // Helper to draw exactly count cards safely
    List<CardModel> draw(int count) {
      final drawn = deck.sublist(deckIndex, deckIndex + count);
      deckIndex += count;
      return drawn;
    }

    // 1. Deal local human
    final localHand = draw(handSize);
    final players = <PlayerModel>[
      PlayerModel(
        id: localId,
        displayName: 'You',
        tablePosition: TablePosition.bottom,
        hand: localHand,
        cardCount: localHand.length,
        isConnected: true,
        isActiveTurn: true,
        isSkipped: false,
      ),
    ];

    // 2. Deal AIs — positions cycle through the three non-bottom slots so that
    //    games with more than 4 players remain compatible with the engine.
    //    Bust mode ignores tablePosition for display (uses colorIndex instead).
    const aiPositionCycle = [
      TablePosition.top,
      TablePosition.left,
      TablePosition.right,
    ];

    for (int i = 0; i < totalPlayers - 1; i++) {
      final aiHand = draw(handSize);
      players.add(PlayerModel(
        id: 'player-${i + 2}',
        displayName: aiNames['player-${i + 2}'] ?? 'Player ${i + 2}',
        tablePosition: aiPositionCycle[i % aiPositionCycle.length],
        hand: aiHand,
        cardCount: aiHand.length,
        isConnected: true,
        isActiveTurn: false,
        isSkipped: false,
      ));
    }

    final discardTop = draw(1).first;
    final drawPile = deck.sublist(deckIndex);

    final state = GameState(
      sessionId: 'demo-session',
      phase: GamePhase.playing,
      players: players,
      currentPlayerId: localId,
      direction: PlayDirection.clockwise,
      discardTopCard: discardTop,
      discardSecondCard: null,
      drawPileCount: drawPile.length,
      activePenaltyCount: 0,
      suitLock: null,
      queenSuitLock: null,
      winnerId: null,
      lastUpdatedAt: 0,
    );

    return (state, drawPile);
  }
}
