// Mocks generated by Mockito 5.4.5 from annotations
// in last_cards/test/core/helpers/network_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter/foundation.dart' as _i2;
import 'package:last_cards/core/models/game_event.dart' as _i6;
import 'package:last_cards/core/network/game_event_handler.dart' as _i5;
import 'package:last_cards/core/network/websocket_client.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeValueNotifier_0<T> extends _i1.SmartFake
    implements _i2.ValueNotifier<T> {
  _FakeValueNotifier_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueListenable_1<T> extends _i1.SmartFake
    implements _i2.ValueListenable<T> {
  _FakeValueListenable_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WebSocketClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketClient extends _i1.Mock implements _i3.WebSocketClient {
  @override
  _i2.ValueNotifier<bool> get reconnectExhausted =>
      (super.noSuchMethod(
            Invocation.getter(#reconnectExhausted),
            returnValue: _FakeValueNotifier_0<bool>(
              this,
              Invocation.getter(#reconnectExhausted),
            ),
            returnValueForMissingStub: _FakeValueNotifier_0<bool>(
              this,
              Invocation.getter(#reconnectExhausted),
            ),
          )
          as _i2.ValueNotifier<bool>);

  @override
  set onConnectedAfterReconnect(void Function()? _onConnectedAfterReconnect) =>
      super.noSuchMethod(
        Invocation.setter(
          #onConnectedAfterReconnect,
          _onConnectedAfterReconnect,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Stream<String> get messages =>
      (super.noSuchMethod(
            Invocation.getter(#messages),
            returnValue: _i4.Stream<String>.empty(),
            returnValueForMissingStub: _i4.Stream<String>.empty(),
          )
          as _i4.Stream<String>);

  @override
  _i2.ValueListenable<_i3.WsConnectionState> get connectionState =>
      (super.noSuchMethod(
            Invocation.getter(#connectionState),
            returnValue: _FakeValueListenable_1<_i3.WsConnectionState>(
              this,
              Invocation.getter(#connectionState),
            ),
            returnValueForMissingStub:
                _FakeValueListenable_1<_i3.WsConnectionState>(
                  this,
                  Invocation.getter(#connectionState),
                ),
          )
          as _i2.ValueListenable<_i3.WsConnectionState>);

  @override
  _i4.Future<void> connect({Uri? uri}) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [], {#uri: uri}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  bool send(String? jsonPayload) =>
      (super.noSuchMethod(
            Invocation.method(#send, [jsonPayload]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [GameEventHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameEventHandler extends _i1.Mock implements _i5.GameEventHandler {
  @override
  _i4.Stream<_i6.GameEvent> get events =>
      (super.noSuchMethod(
            Invocation.getter(#events),
            returnValue: _i4.Stream<_i6.GameEvent>.empty(),
            returnValueForMissingStub: _i4.Stream<_i6.GameEvent>.empty(),
          )
          as _i4.Stream<_i6.GameEvent>);

  @override
  _i4.Stream<_i6.StateSnapshotEvent> get stateSnapshots =>
      (super.noSuchMethod(
            Invocation.getter(#stateSnapshots),
            returnValue: _i4.Stream<_i6.StateSnapshotEvent>.empty(),
            returnValueForMissingStub:
                _i4.Stream<_i6.StateSnapshotEvent>.empty(),
          )
          as _i4.Stream<_i6.StateSnapshotEvent>);

  @override
  _i4.Stream<_i6.CardPlayedEvent> get cardPlays =>
      (super.noSuchMethod(
            Invocation.getter(#cardPlays),
            returnValue: _i4.Stream<_i6.CardPlayedEvent>.empty(),
            returnValueForMissingStub: _i4.Stream<_i6.CardPlayedEvent>.empty(),
          )
          as _i4.Stream<_i6.CardPlayedEvent>);

  @override
  _i4.Stream<_i6.CardDrawnEvent> get cardDraws =>
      (super.noSuchMethod(
            Invocation.getter(#cardDraws),
            returnValue: _i4.Stream<_i6.CardDrawnEvent>.empty(),
            returnValueForMissingStub: _i4.Stream<_i6.CardDrawnEvent>.empty(),
          )
          as _i4.Stream<_i6.CardDrawnEvent>);

  @override
  _i4.Stream<_i6.TurnChangedEvent> get turnChanges =>
      (super.noSuchMethod(
            Invocation.getter(#turnChanges),
            returnValue: _i4.Stream<_i6.TurnChangedEvent>.empty(),
            returnValueForMissingStub: _i4.Stream<_i6.TurnChangedEvent>.empty(),
          )
          as _i4.Stream<_i6.TurnChangedEvent>);

  @override
  _i4.Stream<_i6.PenaltyAppliedEvent> get penalties =>
      (super.noSuchMethod(
            Invocation.getter(#penalties),
            returnValue: _i4.Stream<_i6.PenaltyAppliedEvent>.empty(),
            returnValueForMissingStub:
                _i4.Stream<_i6.PenaltyAppliedEvent>.empty(),
          )
          as _i4.Stream<_i6.PenaltyAppliedEvent>);

  @override
  _i4.Stream<_i6.RoomCreatedEvent> get roomCreated =>
      (super.noSuchMethod(
            Invocation.getter(#roomCreated),
            returnValue: _i4.Stream<_i6.RoomCreatedEvent>.empty(),
            returnValueForMissingStub: _i4.Stream<_i6.RoomCreatedEvent>.empty(),
          )
          as _i4.Stream<_i6.RoomCreatedEvent>);

  @override
  _i4.Stream<_i6.SuitChoiceRequiredEvent> get suitChoiceRequired =>
      (super.noSuchMethod(
            Invocation.getter(#suitChoiceRequired),
            returnValue: _i4.Stream<_i6.SuitChoiceRequiredEvent>.empty(),
            returnValueForMissingStub:
                _i4.Stream<_i6.SuitChoiceRequiredEvent>.empty(),
          )
          as _i4.Stream<_i6.SuitChoiceRequiredEvent>);

  @override
  _i4.Stream<_i6.JokerChoiceRequiredEvent> get jokerChoiceRequired =>
      (super.noSuchMethod(
            Invocation.getter(#jokerChoiceRequired),
            returnValue: _i4.Stream<_i6.JokerChoiceRequiredEvent>.empty(),
            returnValueForMissingStub:
                _i4.Stream<_i6.JokerChoiceRequiredEvent>.empty(),
          )
          as _i4.Stream<_i6.JokerChoiceRequiredEvent>);

  @override
  _i4.Stream<_i6.TurnTimeoutEvent> get turnTimeouts =>
      (super.noSuchMethod(
            Invocation.getter(#turnTimeouts),
            returnValue: _i4.Stream<_i6.TurnTimeoutEvent>.empty(),
            returnValueForMissingStub: _i4.Stream<_i6.TurnTimeoutEvent>.empty(),
          )
          as _i4.Stream<_i6.TurnTimeoutEvent>);

  @override
  _i4.Stream<_i6.ReshuffleEvent> get reshuffles =>
      (super.noSuchMethod(
            Invocation.getter(#reshuffles),
            returnValue: _i4.Stream<_i6.ReshuffleEvent>.empty(),
            returnValueForMissingStub: _i4.Stream<_i6.ReshuffleEvent>.empty(),
          )
          as _i4.Stream<_i6.ReshuffleEvent>);

  @override
  _i4.Stream<_i6.SessionConfigEvent> get sessionConfigs =>
      (super.noSuchMethod(
            Invocation.getter(#sessionConfigs),
            returnValue: _i4.Stream<_i6.SessionConfigEvent>.empty(),
            returnValueForMissingStub:
                _i4.Stream<_i6.SessionConfigEvent>.empty(),
          )
          as _i4.Stream<_i6.SessionConfigEvent>);

  @override
  _i4.Stream<_i6.ErrorEvent> get errors =>
      (super.noSuchMethod(
            Invocation.getter(#errors),
            returnValue: _i4.Stream<_i6.ErrorEvent>.empty(),
            returnValueForMissingStub: _i4.Stream<_i6.ErrorEvent>.empty(),
          )
          as _i4.Stream<_i6.ErrorEvent>);

  @override
  _i4.Stream<_i6.QuickChatEvent> get quickChats =>
      (super.noSuchMethod(
            Invocation.getter(#quickChats),
            returnValue: _i4.Stream<_i6.QuickChatEvent>.empty(),
            returnValueForMissingStub: _i4.Stream<_i6.QuickChatEvent>.empty(),
          )
          as _i4.Stream<_i6.QuickChatEvent>);

  @override
  _i4.Stream<_i6.InvalidPlayPenaltyEvent> get invalidPlayPenalties =>
      (super.noSuchMethod(
            Invocation.getter(#invalidPlayPenalties),
            returnValue: _i4.Stream<_i6.InvalidPlayPenaltyEvent>.empty(),
            returnValueForMissingStub:
                _i4.Stream<_i6.InvalidPlayPenaltyEvent>.empty(),
          )
          as _i4.Stream<_i6.InvalidPlayPenaltyEvent>);

  @override
  _i4.Stream<_i6.LastCardsPressedEvent> get lastCardsPressed =>
      (super.noSuchMethod(
            Invocation.getter(#lastCardsPressed),
            returnValue: _i4.Stream<_i6.LastCardsPressedEvent>.empty(),
            returnValueForMissingStub:
                _i4.Stream<_i6.LastCardsPressedEvent>.empty(),
          )
          as _i4.Stream<_i6.LastCardsPressedEvent>);

  @override
  _i4.Stream<_i6.LastCardsBluffEvent> get lastCardsBluffs =>
      (super.noSuchMethod(
            Invocation.getter(#lastCardsBluffs),
            returnValue: _i4.Stream<_i6.LastCardsBluffEvent>.empty(),
            returnValueForMissingStub:
                _i4.Stream<_i6.LastCardsBluffEvent>.empty(),
          )
          as _i4.Stream<_i6.LastCardsBluffEvent>);

  @override
  _i4.Stream<_i6.GameMomentEvent> get gameMoments =>
      (super.noSuchMethod(
            Invocation.getter(#gameMoments),
            returnValue: _i4.Stream<_i6.GameMomentEvent>.empty(),
            returnValueForMissingStub: _i4.Stream<_i6.GameMomentEvent>.empty(),
          )
          as _i4.Stream<_i6.GameMomentEvent>);

  @override
  bool sendPlayCards(_i6.PlayCardsAction? action) =>
      (super.noSuchMethod(
            Invocation.method(#sendPlayCards, [action]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool sendDrawCard() =>
      (super.noSuchMethod(
            Invocation.method(#sendDrawCard, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool sendDeclareJoker(_i6.DeclareJokerAction? action) =>
      (super.noSuchMethod(
            Invocation.method(#sendDeclareJoker, [action]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool sendEndTurn() =>
      (super.noSuchMethod(
            Invocation.method(#sendEndTurn, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool sendDeclareLastCards() =>
      (super.noSuchMethod(
            Invocation.method(#sendDeclareLastCards, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool sendSuitChoice(_i6.SuitChoiceAction? action) =>
      (super.noSuchMethod(
            Invocation.method(#sendSuitChoice, [action]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool sendQuickChat(_i6.QuickChatAction? action) =>
      (super.noSuchMethod(
            Invocation.method(#sendQuickChat, [action]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
